### ISSUE TITLE
如何在sgx模式下增加python的依赖？

### ISSUE THREAD

**Issue by zzx-QDU** [asterinas/trustflow#80]
您好，我想在teeapps-sgx镜像中安装matplotlib这样原来没有的依赖包，但是直接装到默认位置或者/home/teeapp/python-occlum/lib/下都是不行的，前者matplotlib没有生效，后者则在build occlum时提示：
make: *** No rule to make target '/home/teeapp/occlum/occlum_instance/build/mount/__ROOT/metadata', needed by '/home/teeapp/occlum/occlum_instance/build/.Occlum_sys.json'.  Stop.

请问正确安装新依赖的方式是什么？

**Comment by zzx-QDU** [comment]
第二个错误是我在备份image文件夹失误导致编译时没有image文件夹。

**Comment by zhongtianq** [comment]
可以参考teeapps镜像的build过程：
https://github.com/asterinas/trustflow-teeapps/blob/main/deployment/occlum/Dockerfile

它调用https://github.com/asterinas/trustflow-teeapps/blob/main/scripts/build_occlum.sh构建了一个python环境，安装了依赖包，然后copy_bom将相关环境复制和链接到occlum中去。

**Comment by zhongtianq** [comment]
@zzx-QDU 你指的是这个教程吗？https://www.secretflow.org.cn/zh-CN/docs/trustedflow/0.3.1b0/development/new_component#id10

这个教程是开发新组件，开发完成之后最后是构建teeapps镜像，构建过程就是调用前面说的脚本。所以安装依赖就是在这个脚本中加入你要安装的依赖就可以了。

**Comment by zhongtianq** [comment]
如前面所说，copy python环境到occlum中使用了copy_bom，用法可以参照https://occlum.readthedocs.io/en/latest/tools/copy_bom.html

我们的build过程中用到的copy_bom配置python.yaml内容如下：
```yaml
includes:
  - base.yaml
targets:
  - target: /bin
    createlinks:
      - src: /opt/python-occlum/bin/python3
        linkname: python3
  # python packages
  - target: /opt
    copy: 
      - dirs:
          - /home/teeapp/python-occlum
  - target: /
    copy:
      - from: /home/teeapp/occlum/teeapps/biz
        dirs:
          - secretflow
          - teeapps
        files: 
          - biclassification_eval.py
          - feature_filter.py
          - train_test_split.py
          - lr.py
          - predict.py
          - prediction_bias_eval.py
          - psi.py
          - pearsonr.py
          - vif.py
          - table_statistics.py
          - woe_binning.py
          - woe_substitution.py
          - xgb.py
          - lgbm.py
          - __init__.py
```

可以看到我们将/home/teeapp/python-occlum copy到了/opt下，并且link了/opt/python-occlum/bin/python3到 occlum_instance的image/bin下面。  你可以用类似的方式将所需的依赖安装并copy
